### PR TITLE
Add support for Wyrmling Bones

### PR DESCRIPTION
**Pull request by ghost**
Noticed this was missing when I got a 0 xp prayer chest. Will post screenshots when I get another and verify the changes work.

### CODE REVIEW

**Comment by ghost** [comment]
image
image
image

343 shards @ 5xp = 1715xp
52 bones @ 21 shards @ 5xp = 5460xp
1715xp + 5460xp = 7175

**Comment by bradur** [comment]
Hi and thank you for submitting a PR!

I left out Wyrmling bones on purpose originally but you're correct that it's a needed feature. I've had some other people mention this as well. So I agree that something should be done.

The problem is that Wyrmling bones also contribute to the GE / HA value pool, often a significant percentage of the total. So it might leave the user confused. It was an easy choice to display shards as purely Prayer XP since they provide no monetary value.

I feel like there should be some option of not displaying the bones monetary value when you choose to display their Prayer XP value. What do you think? Or is this a non-issue? I'm not a 100% on this.

**Comment by ghost** [comment]
Appreciate the insight! I play an ironman so that part had not even crossed my mind. Having an additional config option for 'Wymling Bones total display as' I think would work best "Both" "GP" "Prayer". The only question would be what should the default be; GP?

**Comment by bradur** [comment]
Good suggestion! For my use case the default would be "GP" but it should be what the majority expects. Which probably is "Both". That's what your current solution shows, right? I'm happy with that as default as long the other options exist.

**Comment by ghost** [comment]
That's correct, my current PR implementation displays their value under both GP and Prayer. I will add the discussed config option here in a moment with the default being "Both". I agree that having the option is better and preferred.

**Comment by ghost** [comment]
image

Option added.

**Comment by bradur** [comment]
Looks good. So once I merge I need to do a PR to runelite for the plugin to update right? It's my first runelite plugin :P.

**Comment by ghost** [comment]
I've actually never personally contributed but that's my understanding too lol. Same as initially you are just updating the commit hash to point to a new version.

**Comment by bradur** [comment]
Right, that's what I thought. Thanks again!

**Pull request merged**
